# blog.config.yaml
title: "Taman"
description: "Devlog for TUI Pomodoro built with Rust and Ratatui"
theme: "rose-pine"
font: "geist-mono"
# accent: "#c4a7e7"
show_toc: true
show_repo_link: true
ga_id: "G-S9T6754EHK"